/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubHistoryIndexRouteImport } from './routes/sub-history/index'
import { Route as CreditHistoryIndexRouteImport } from './routes/credit-history/index'
import { Route as SubHistoryIdRouteImport } from './routes/sub-history/$id'
import { Route as CreditHistoryIdRouteImport } from './routes/credit-history/$id'

const UserManageLazyRouteImport = createFileRoute('/user-manage')()
const LoginLazyRouteImport = createFileRoute('/login')()
const IndexLazyRouteImport = createFileRoute('/')()

const UserManageLazyRoute = UserManageLazyRouteImport.update({
  id: '/user-manage',
  path: '/user-manage',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/user-manage.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const SubHistoryIndexRoute = SubHistoryIndexRouteImport.update({
  id: '/sub-history/',
  path: '/sub-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditHistoryIndexRoute = CreditHistoryIndexRouteImport.update({
  id: '/credit-history/',
  path: '/credit-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubHistoryIdRoute = SubHistoryIdRouteImport.update({
  id: '/sub-history/$id',
  path: '/sub-history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditHistoryIdRoute = CreditHistoryIdRouteImport.update({
  id: '/credit-history/$id',
  path: '/credit-history/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/user-manage': typeof UserManageLazyRoute
  '/credit-history/$id': typeof CreditHistoryIdRoute
  '/sub-history/$id': typeof SubHistoryIdRoute
  '/credit-history': typeof CreditHistoryIndexRoute
  '/sub-history': typeof SubHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/user-manage': typeof UserManageLazyRoute
  '/credit-history/$id': typeof CreditHistoryIdRoute
  '/sub-history/$id': typeof SubHistoryIdRoute
  '/credit-history': typeof CreditHistoryIndexRoute
  '/sub-history': typeof SubHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/user-manage': typeof UserManageLazyRoute
  '/credit-history/$id': typeof CreditHistoryIdRoute
  '/sub-history/$id': typeof SubHistoryIdRoute
  '/credit-history/': typeof CreditHistoryIndexRoute
  '/sub-history/': typeof SubHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/user-manage'
    | '/credit-history/$id'
    | '/sub-history/$id'
    | '/credit-history'
    | '/sub-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/user-manage'
    | '/credit-history/$id'
    | '/sub-history/$id'
    | '/credit-history'
    | '/sub-history'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/user-manage'
    | '/credit-history/$id'
    | '/sub-history/$id'
    | '/credit-history/'
    | '/sub-history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  UserManageLazyRoute: typeof UserManageLazyRoute
  CreditHistoryIdRoute: typeof CreditHistoryIdRoute
  SubHistoryIdRoute: typeof SubHistoryIdRoute
  CreditHistoryIndexRoute: typeof CreditHistoryIndexRoute
  SubHistoryIndexRoute: typeof SubHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-manage': {
      id: '/user-manage'
      path: '/user-manage'
      fullPath: '/user-manage'
      preLoaderRoute: typeof UserManageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-history/': {
      id: '/sub-history/'
      path: '/sub-history'
      fullPath: '/sub-history'
      preLoaderRoute: typeof SubHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-history/': {
      id: '/credit-history/'
      path: '/credit-history'
      fullPath: '/credit-history'
      preLoaderRoute: typeof CreditHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-history/$id': {
      id: '/sub-history/$id'
      path: '/sub-history/$id'
      fullPath: '/sub-history/$id'
      preLoaderRoute: typeof SubHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-history/$id': {
      id: '/credit-history/$id'
      path: '/credit-history/$id'
      fullPath: '/credit-history/$id'
      preLoaderRoute: typeof CreditHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  UserManageLazyRoute: UserManageLazyRoute,
  CreditHistoryIdRoute: CreditHistoryIdRoute,
  SubHistoryIdRoute: SubHistoryIdRoute,
  CreditHistoryIndexRoute: CreditHistoryIndexRoute,
  SubHistoryIndexRoute: SubHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
